import * as Blockly from 'blockly';

export const IngeniablesTheme = Blockly.Theme.defineTheme('ingeniables', {
  name: 'ingeniables',
  base: Blockly.Themes.Classic,
  blockStyles: {
    logic_blocks: { colourPrimary: '#5b6da7', colourSecondary: '#4a5d96', colourTertiary: '#3e4f7a' },
    loop_blocks: { colourPrimary: '#49a563', colourSecondary: '#3d9154', colourTertiary: '#2e7a42' },
    math_blocks: { colourPrimary: '#4ECDC4', colourSecondary: '#3dbdb4', colourTertiary: '#2ea89f' },
    text_blocks: { colourPrimary: '#E8A838', colourSecondary: '#d49730', colourTertiary: '#b88028' },
    variable_blocks: { colourPrimary: '#E07C38', colourSecondary: '#cc6e2e', colourTertiary: '#b36026' },
    list_blocks: { colourPrimary: '#E05676', colourSecondary: '#cc4a68', colourTertiary: '#b33e5a' },
    procedure_blocks: { colourPrimary: '#9B59B6', colourSecondary: '#8a4da3', colourTertiary: '#764190' },
    sensor_blocks: { colourPrimary: '#2C3E50', colourSecondary: '#253545', colourTertiary: '#1e2c3a' },
    actuator_blocks: { colourPrimary: '#F39C12', colourSecondary: '#db8c0f', colourTertiary: '#c07a0d' },
    time_blocks: { colourPrimary: '#3498DB', colourSecondary: '#2d88c7', colourTertiary: '#2678b3' },
    serial_blocks: { colourPrimary: '#27AE60', colourSecondary: '#229a54', colourTertiary: '#1d8648' },
    io_blocks: { colourPrimary: '#2980B9', colourSecondary: '#2472a4', colourTertiary: '#1f648f' },
    display_blocks: { colourPrimary: '#8E44AD', colourSecondary: '#7d3c9a', colourTertiary: '#6c3487' },
    neopixel_blocks: { colourPrimary: '#E74C3C', colourSecondary: '#cf4436', colourTertiary: '#b73c30' },
    motor_blocks: { colourPrimary: '#D35400', colourSecondary: '#bb4a00', colourTertiary: '#a34100' },
    wifi_blocks: { colourPrimary: '#1ABC9C', colourSecondary: '#17a88c', colourTertiary: '#14947c' },
    bluetooth_blocks: { colourPrimary: '#2C82C9', colourSecondary: '#2774b4', colourTertiary: '#22669f' },
    setup_blocks: { colourPrimary: '#4E9995', colourSecondary: '#458a86', colourTertiary: '#3c7b77' },
  },
  categoryStyles: {
    logic_category: { colour: '#5b6da7' },
    control_category: { colour: '#49a563' },
    math_category: { colour: '#4ECDC4' },
    text_category: { colour: '#E8A838' },
    variable_category: { colour: '#E07C38' },
    list_category: { colour: '#E05676' },
    procedure_category: { colour: '#9B59B6' },
    sensor_category: { colour: '#2C3E50' },
    actuator_category: { colour: '#F39C12' },
    time_category: { colour: '#3498DB' },
    serial_category: { colour: '#27AE60' },
    io_category: { colour: '#2980B9' },
    display_category: { colour: '#8E44AD' },
    neopixel_category: { colour: '#E74C3C' },
    motor_category: { colour: '#D35400' },
    wifi_category: { colour: '#1ABC9C' },
    bluetooth_category: { colour: '#2C82C9' },
  },
  componentStyles: {
    workspaceBackgroundColour: '#fafafa',
    toolboxBackgroundColour: '#ffffff',
    toolboxForegroundColour: '#1E1E1C',
    flyoutBackgroundColour: '#f9fafb',
    flyoutForegroundColour: '#1E1E1C',
    flyoutOpacity: 0.95,
    scrollbarColour: '#d1d5db',
    scrollbarOpacity: 0.7,
    insertionMarkerColour: '#FFD002',
    insertionMarkerOpacity: 0.5,
    cursorColour: '#FFD002',
  },
  fontStyle: {
    family: 'Noto Sans, sans-serif',
    weight: '500',
    size: 12,
  },
});
